name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: mamba-org/setup-micromamba@ce51e99f4bb8a82ab7158c4dc59ef4634c59c4f9 # v3.1.0
        with:
          environment-file: environment.yml
          environment-name: ornax
          create-args: python=3.11

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          pip install --no-deps --no-build-isolation -e .

      - name: test
        shell: bash -l {0}
        run: |
          export JAX_ENABLE_X64=1
          pytest -vv tests
